### ISSUE TITLE
Security Issue: Cookie is not secure

### ISSUE THREAD

**Issue by yonjah** [ylorenzana/node-express-api-auth#4]
https://github.com/ylorenzana/node-express-api-auth/blob/master/server/routes/users.js#L26
And Line 
https://github.com/ylorenzana/node-express-api-auth/blob/master/server/routes/users.js#L83

secure option is totally commented out and though comment says this will be set to true in production
it is a not true.
Best thing will be to actually change it to be secure if NODE_ENV is not in development mode (and not the other way around as many clueless devs forget to change NODE_ENV to production).

**Comment by ylorenzana** [comment]
https://github.com/ylorenzana/node-express-api-auth/pull/13
