### ISSUE TITLE
Security Issue: Add CSRF protection

### ISSUE THREAD

**Issue by yonjah** [ylorenzana/node-express-api-auth#7]
Currently the only protection against CSRF is by using SameSite cookie.
This is good but there are still "modern" browsers that don't support it so many users will be unprotected
proper CSRF protection is required

**Comment by ylorenzana** [comment]
I agree that the sameSite is not enough as browser support is iffy. I am working on additional CSRF mitigations right now.

**Comment by ylorenzana** [comment]
Just pushed up changes to a new branch: https://github.com/ylorenzana/node-express-api-auth/tree/feature-csrf-tokens let me know what the implementation looks like. CSRF token has to be provided in header: 'CSRF-token' for csrf protected routes, in this case, only the api/users/me route has it.

**Comment by yonjah** [comment]
The general implementation looks good.
I added a few comments to the code.

One thing I will really consider doing now is adding in tests.
The code is getting more complex and the earlier you'll add tests in the easier it will be.

**Comment by ylorenzana** [comment]
Some more changes: https://github.com/ylorenzana/node-express-api-auth/commit/d2e3e8b926b2ec7b11d928489bba1b4d4d40f96d

**Comment by yonjah** [comment]
@ylorenzana Added a few comments. 
Might make it easier if you'll create a separate branch for each new feature than add a pull request to the branch. So we can discuss changes in the pull request thread
